name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: [self-hosted]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for better relevancy of analysis

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Specify the Node.js version you want (you can change this as needed)

      - name: Install dependencies (npm)
        run: npm install  # This installs the dependencies listed in package.json

      - name: Trivy file scan
        run: trivy fs . > trivyfs.txt

     

      - uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
